#!/bin/sh

# binaries
chmod +x $HOME/.bin
go build -o align align.go && mv align $HOME/.bin
ln -sf $(pwd)/pass $HOME/.bin/pass

# sublime plugins
subldir="$HOME/Library/Application Support/Sublime Text/Packages/User"
cp cfmt.py  "$subldir/cfmt.py"
cp gofmt.py "$subldir/gofmt.py"
